[package]
name = "grepy"
version = "0.1.0"
authors = ["Tomasz Kopacki <tomasz@kopacki.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
clap = "3.0.0-beta.2"
regex = "1.5.4"