[workspace]
members = [
    "cli-101",
    "marketplace",
    "basic-marketplace",
    "keyrings",
    "caching",
]

exclude = [
    "cargo-examples/dependencies",
    "cargo-examples/runtime",
    "smart-contractss",
]