[package]
name = "caching"
version = "0.1.0"
authors = ["Tomasz Kopacki <tomasz@kopacki.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
