[package]
name = "cli-101"
version = "0.1.0"
authors = ["Tomasz Kopacki <tk-o@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
